# Generated by Django 5.2 on 2025-04-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='calculation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
