# Generated by Django 5.2 on 2025-04-29 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recurrence_calculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='after_values',
            field=models.JSONField(blank=True, null=True, default=None),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_values',
            field=models.JSONField(blank=True, null=True, default=None),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='row_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='table_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=20, default='unknown'),
        ),
    ]
